name: Cache

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v5

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.22'

    - name: Check code style
      run : make goCheck

    - name: Test Correct Work
      run: make testCacheCorrect
   
    - name: Test Jitter
      run: make testCacheJitter

    - name: Test Race
      run: make testCacheRace

